create database schooldatabase;
use schooldatabase;
CREATE TABLE IF NOT EXISTS students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_name VARCHAR(255),
    student_age INT,
    student_gender VARCHAR(50),
    nationality VARCHAR(50),
    religion VARCHAR(50),
    student_order VARCHAR(50),
    student_class VARCHAR(50),
    student_stream VARCHAR(50),
    entry_year INT,
    student_adm_number VARCHAR(20),
    student_code VARCHAR(20),
    color VARCHAR(100),
    father_name VARCHAR(255),
    father_occupation VARCHAR(100),
    father_contact VARCHAR(20),
    father_alt_contact VARCHAR(20),
    mother_name VARCHAR(255),
    mother_occupation VARCHAR(100),
    mother_contact VARCHAR(20),
    mother_alt_contact VARCHAR(20),
    guardian_name VARCHAR(255),
    guardian_occupation VARCHAR(100),
    guardian_contact VARCHAR(20),
    guardian_alt_contact VARCHAR(20),
    residential_area VARCHAR(255),
    zone VARCHAR(50),
    road VARCHAR(255),
    health_problem VARCHAR(255),
    emergency_person VARCHAR(255),
    other_information VARCHAR(255),
    date_of_birth DATE,
    image VARCHAR(500),
    registration_date DATE,
    created_by INT
);
